import = [
"~/.config/alacritty/themes/themes/tokyo-night.toml",
]

shell = "/usr/local/bin/fish"

[ env ]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 0 }
decorations = "None"
opacity = 0.80
decorations_theme_variant = "Dark"

[font]
normal.family = "0xProto Nerd Font"
size = 10

